export {default as Header} from './Header/Header'
export {default as Footer} from './Footer/Footer'
export {default as Hero} from './Hero/Hero'
export {default as Process} from './Process/Process'
export {default as Partners} from './Partners/Partners'